### ISSUE TITLE
UI theme suggestion

### ISSUE THREAD

**Issue by izayl** [hooopo/hackershare#39]
![image](https://user-images.githubusercontent.com/10740043/92955068-14894180-f497-11ea-9537-e7ffc994a10d.png)

https://www.figma.com/file/6UmYBUDCy2K1paIPy3n5VW/hackershare?node-id=0%3A1

I make a new theme use figma, hope this helps.

**Comment by songhuangcn** [comment]
Thank you, this design is beautiful, we will update the website UI referring to it.

Thank you again for your contribution.
